---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: golang
    when:
      event: [push]
    commands:
      - go get -v ./...

  - name: gofmt
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - test -z "$(gofmt -l -d . | tee /dev/stderr)"

  - name: test
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - go test -v ./...

  - name: build
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - go build .

  - name: docker
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    depends_on:
      - test
      - build
      - gofmt
    settings:
      registry: https://registry.abakus.no
      repo: registry.abakus.no/webkom/readme-as-a-function
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
