---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: golang
    when:
      event: [push]
    commands:
      - go get -v ./...

  - name: gofmt
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - test -z "$(gofmt -l -d . | tee /dev/stderr)"

  - name: test
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - go test -v ./...

  - name: build
    image: golang
    depends_on:
      - setup
    when:
      event: [push]
    commands:
      - go build .

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    depends_on:
      - test
      - build
      - gofmt
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/readme-as-a-function
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - faas-fn
      limit: esas
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    depends_on:
      - docker
